'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';

type RecordRow={id:string,date:string,fy:string,month:string,quarter:string,status:string,remarks:string,name?:string,mobile?:string,email?:string,designation?:string,idNo?:string,otherDetails?:string,member?:'Individual'|'Corporate'|'Institutional',sponsorship?:number,expenditure?:number,pacc?:number,ad?:number,event?:string,training?:string,article?:string,st?:boolean,ap?:boolean,project?:boolean,nominations?:number};
const months=['Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar'];
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const blank=(fy='FY 2025-26'):RecordRow=>({id:'',date:new Date().toISOString().slice(0,10),fy,month:'',quarter:'',status:'Active',remarks:'',sponsorship:0,expenditure:0,pacc:0,ad:0,nominations:0});

function Bars({values,color='#ef4438'}:{values:number[],color?:string}){const max=Math.max(...values,1);return <div className="bars">{values.map((v,i)=><div className="bar" key={months[i]} title={`${months[i]}: ${v}`}><i style={{height:`${Math.max(v?12:2,v/max*100)}%`,background:color}}/><small>{months[i]}</small></div>)}</div>}
function Metric({label,value,tone='red',note}:{label:string,value:string|number,tone?:string,note?:string}){return <article className={`metric ${tone}`}><span>{label}<i>↗</i></span><strong>{value}</strong>{note&&<small>{note}</small>}</article>}
function Section({n,title,desc,id,children}:{n:string,title:string,desc:string,id:string,children:React.ReactNode}){return <section id={id}><div className="sectiontitle"><div><span>{n}</span><h2>{title}</h2></div><p>{desc}</p></div>{children}</section>}

export default function Home(){
  const[fy,setFy]=useState('FY 2025-26');
  const[q,setQ]=useState('');
  const[records,setRecords]=useState<RecordRow[]>([]);
  const[loading,setLoading]=useState(true);
  const[modal,setModal]=useState(false);
  const[editing,setEditing]=useState<RecordRow>(blank());
  const[saving,setSaving]=useState(false);
  const[notice,setNotice]=useState('');

  const load=async()=>{setLoading(true);try{const res=await fetch('/api/records',{cache:'no-store'});if(!res.ok)throw new Error();setRecords(await res.json())}catch{setNotice('Records load nahi ho paaye. Please refresh karein.')}finally{setLoading(false)}};
  useEffect(()=>{let cancelled=false;(async()=>{try{const res=await fetch('/api/records',{cache:'no-store'});if(!res.ok)throw new Error();const data=await res.json() as RecordRow[];if(!cancelled)setRecords(data)}catch{if(!cancelled)setNotice('Records load nahi ho paaye. Please refresh karein.')}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
  const rows=useMemo(()=>records.filter(r=>r.fy===fy&&r.status!=='Cancelled'),[records,fy]);
  const count=(fn:(r:RecordRow)=>boolean)=>rows.filter(fn).length;
  const sum=(key:keyof RecordRow)=>rows.reduce((a,r)=>a+Number(r[key]||0),0);
  const monthly=(key:keyof RecordRow,countIt=false)=>months.map(m=>rows.filter(r=>r.month===m).reduce((a,r)=>a+(countIt?(r[key]?1:0):Number(r[key]||0)),0));
  const individual=count(r=>r.member==='Individual'),corporate=count(r=>r.member==='Corporate'),institutional=count(r=>r.member==='Institutional');
  const sponsorship=sum('sponsorship'),expenditure=sum('expenditure');
  const visible=rows.filter(r=>(r.id+r.remarks+r.status+(r.name||'')+(r.mobile||'')+(r.email||'')+(r.idNo||'')).toLowerCase().includes(q.toLowerCase()));
  const field=<K extends keyof RecordRow>(key:K,value:RecordRow[K])=>setEditing(old=>({...old,[key]:value}));
  const openAdd=()=>{setEditing(blank(fy));setModal(true)};
  const openEdit=(row:RecordRow)=>{setEditing({...row});setModal(true)};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!editing.date||!editing.remarks.trim())return;setSaving(true);try{const method=editing.id?'PUT':'POST';const res=await fetch('/api/records',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});if(!res.ok)throw new Error();setModal(false);setNotice(editing.id?'Record successfully update ho gaya.':'New record successfully add ho gaya.');await load()}catch{setNotice('Record save nahi hua. Dobara try karein.')}finally{setSaving(false)}};
  const remove=async(row:RecordRow)=>{if(!confirm(`${row.id} delete karna hai? Yeh action undo nahi hoga.`))return;try{const res=await fetch(`/api/records?id=${encodeURIComponent(row.id)}`,{method:'DELETE'});if(!res.ok)throw new Error();setNotice('Record delete ho gaya.');await load()}catch{setNotice('Record delete nahi hua. Dobara try karein.')}};
  const download=()=>{const csvValue=(value:string|number|undefined)=>`"${String(value??'').replaceAll('"','""')}"`;const csv=['Record ID,Date,FY,Quarter,Status,Remarks',...visible.map(r=>[r.id,r.date,r.fy,r.quarter,r.status,r.remarks].map(csvValue).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`FSAI-${fy}.csv`;a.click();URL.revokeObjectURL(url)};

  return <div className="shell"><aside><div className="brand"><img src="/fsai-logo.svg" alt="FSAI logo" className="brand-logo" /><span><strong>FSAI</strong>Performance Hub</span></div><nav>{[['⌂','Overview','overview'],['♙','Membership','membership'],['₹','Financials','financial'],['◫','Activities','activities'],['◇','Initiatives','initiatives'],['≡','Records','records']].map((x,i)=><a className={i?'':'active'} href={`#${x[2]}`} key={x[1]}><i>{x[0]}</i>{x[1]}</a>)}</nav><div className="source"><b>Live database</b><span>Records auto-saved</span><small>{records.length} total records</small></div></aside><main>
    <header id="overview"><div><p className="eyebrow">MANAGEMENT OVERVIEW</p><h1>Performance Dashboard</h1><p>Fire & Security Association of India</p></div><div className="controls"><label>Financial Year<select value={fy} onChange={e=>setFy(e.target.value)}><option>FY 2025-26</option><option>FY 2026-27</option></select></label><button className="secondary" onClick={download}>⇩ Export</button><button onClick={openAdd}>＋ Add record</button></div></header>
    <div className="fresh"><span><i/>{loading?'Records loading…':'Live records · changes automatically saved'}</span><span>{rows.length} active records · {fy}</span></div>{notice&&<div className="notice" role="status"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
    <Section n="01" title="Membership" desc={`Active member composition for ${fy}`} id="membership"><div className="metrics"><Metric label="Individual members" value={individual}/><Metric label="Corporate members" value={corporate} tone="navy"/><Metric label="Institutional members" value={institutional} tone="gold"/><Metric label="Total members" value={individual+corporate+institutional} tone="green" note="Across all categories"/></div></Section>
    <Section n="02" title="Financial performance" desc="Sponsorship, expenditure and surplus" id="financial"><div className="metrics"><Metric label="Sponsorship collected" value={money(sponsorship)}/><Metric label="Expenditure done" value={money(expenditure)} tone="navy"/><Metric label="Surplus" value={money(sponsorship-expenditure)} tone="green"/><Metric label="PACC 2027 sponsorship" value={money(sum('pacc'))} tone="gold"/></div><div className="charts"><article className="card wide"><div className="cardhead"><div><h3>Monthly cash movement</h3><p>Sponsorship collected</p></div><em>Apr — Mar</em></div><Bars values={monthly('sponsorship')}/></article><article className="card"><h3>Financial snapshot</h3><p>Use of sponsorship funds</p><div className="snapshot"><strong>{sponsorship?Math.round((sponsorship-expenditure)/sponsorship*100):0}%</strong><span>retained as surplus</span></div><div className="progress"><i style={{width:`${sponsorship?Math.max(0,(sponsorship-expenditure)/sponsorship*100):0}%`}}/></div><div className="split"><span>Collected<b>{money(sponsorship)}</b></span><span>Spent<b>{money(expenditure)}</b></span></div></article></div></Section>
    <Section n="03" title="Activities" desc="Events, learning and journal activity" id="activities"><div className="metrics"><Metric label="Events conducted" value={count(r=>!!r.event)}/><Metric label="Training programs" value={count(r=>!!r.training)} tone="navy"/><Metric label="Articles shared" value={count(r=>!!r.article)} tone="gold"/><Metric label="Ad contribution" value={money(sum('ad'))} tone="green"/></div><div className="charts three"><article className="card"><h3>Events</h3><p>Monthly count</p><Bars values={monthly('event',true)}/></article><article className="card"><h3>Training & awareness</h3><p>Monthly count</p><Bars values={monthly('training',true)} color="#13263c"/></article><article className="card"><h3>Journal activity</h3><p>Articles shared</p><Bars values={monthly('article',true)} color="#d79c2b"/></article></div></Section>
    <Section n="04" title="Initiatives & awards" desc="Suraksha Index and FIST Awards" id="initiatives"><div className="metrics"><Metric label="Suraksha trainings" value={count(r=>!!r.st)}/><Metric label="Suraksha APs added" value={count(r=>!!r.ap)} tone="navy"/><Metric label="New projects" value={count(r=>!!r.project)} tone="green"/><Metric label="FIST nominations" value={sum('nominations')} tone="gold"/></div></Section>
    <Section n="05" title="Activity records" desc="Professional contact and performance records" id="records"><article className="tablecard"><div className="tabletools"><div><h3>Master records</h3><p>{visible.length} records in {fy}</p></div><div className="recordtools"><label>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, mobile, email or ID"/></label><button onClick={openAdd}>＋ Add record</button></div></div><div className="scroll"><table><thead><tr><th>Member / Record</th><th>Contact</th><th>Designation</th><th>Status</th><th>Activity / remarks</th><th>Actions</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><div className="person"><span>{(r.name||'R').slice(0,1).toUpperCase()}</span><div><b>{r.name||r.id}</b><small>{r.idNo||r.id}</small></div></div></td><td><div className="contact"><span>{r.mobile||'—'}</span><small>{r.email||new Date(r.date).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</small></div></td><td>{r.designation||r.member||'—'}</td><td><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></td><td><div className="remarks">{r.remarks}{r.otherDetails&&<small>{r.otherDetails}</small>}</div></td><td><div className="actions"><button onClick={()=>openEdit(r)}>Edit</button><button className="danger" onClick={()=>remove(r)}>Delete</button></div></td></tr>)}</tbody></table>{!loading&&!visible.length&&<div className="empty">Is financial year mein koi matching record nahi mila.</div>}</div></article></Section>
    <footer><span>FSAI Performance Hub</span><span>Secure live database</span></footer>
  </main>
  {modal&&<div className="modalback" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={save}><div className="modalhead"><div><p className="eyebrow">RECORD MANAGEMENT</p><h2>{editing.id?'Edit professional record':'Add professional record'}</h2><span>Contact, identification and performance details</span></div><button type="button" onClick={()=>setModal(false)} aria-label="Close">×</button></div><div className="formsection"><h3><i>01</i> Personal & Contact Information</h3><div className="formgrid">
    <label>Full Name<input value={editing.name||''} onChange={e=>field('name',e.target.value||undefined)} placeholder="e.g. Rajesh Sharma"/></label><label>Mobile No.<input type="tel" inputMode="numeric" value={editing.mobile||''} onChange={e=>field('mobile',e.target.value||undefined)} placeholder="+91 98765 43210"/></label>
    <label>Email ID<input type="email" value={editing.email||''} onChange={e=>field('email',e.target.value||undefined)} placeholder="name@company.com"/></label><label>Designation<input value={editing.designation||''} onChange={e=>field('designation',e.target.value||undefined)} placeholder="e.g. Safety Manager"/></label>
    <label>ID No.<input value={editing.idNo||''} onChange={e=>field('idNo',e.target.value||undefined)} placeholder="Membership / Employee ID"/></label><label>Member Type<select value={editing.member||''} onChange={e=>field('member',(e.target.value||undefined) as RecordRow['member'])}><option value="">Not applicable</option><option>Individual</option><option>Corporate</option><option>Institutional</option></select></label>
    <label className="full">Other Details<textarea rows={3} value={editing.otherDetails||''} onChange={e=>field('otherDetails',e.target.value||undefined)} placeholder="Address, company, chapter or any additional information"/></label>
  </div></div><div className="formsection"><h3><i>02</i> Record & Performance Details</h3><div className="formgrid">
    <label>Date<input required type="date" value={editing.date} onChange={e=>field('date',e.target.value)}/></label><label>Financial Year<select value={editing.fy} onChange={e=>field('fy',e.target.value)}><option>FY 2025-26</option><option>FY 2026-27</option></select></label>
    <label>Status<select value={editing.status} onChange={e=>field('status',e.target.value)}><option>Active</option><option>Completed</option><option>Cancelled</option></select></label><label>Record ID<input value={editing.id||'Automatically generated'} disabled/></label>
    <label className="full">Remarks / Activity<input required value={editing.remarks} onChange={e=>field('remarks',e.target.value)} placeholder="Record ka short description"/></label>
    <label>Sponsorship (₹)<input min="0" type="number" value={editing.sponsorship||''} onChange={e=>field('sponsorship',Number(e.target.value))}/></label><label>Expenditure (₹)<input min="0" type="number" value={editing.expenditure||''} onChange={e=>field('expenditure',Number(e.target.value))}/></label><label>PACC 2027 (₹)<input min="0" type="number" value={editing.pacc||''} onChange={e=>field('pacc',Number(e.target.value))}/></label><label>Ad Contribution (₹)<input min="0" type="number" value={editing.ad||''} onChange={e=>field('ad',Number(e.target.value))}/></label>
    <label>Event Name<input value={editing.event||''} onChange={e=>field('event',e.target.value||undefined)}/></label><label>Training Program<input value={editing.training||''} onChange={e=>field('training',e.target.value||undefined)}/></label><label>Article Name<input value={editing.article||''} onChange={e=>field('article',e.target.value||undefined)}/></label><label>FIST Nominations<input min="0" type="number" value={editing.nominations||''} onChange={e=>field('nominations',Number(e.target.value))}/></label>
  </div><div className="checks"><label><input type="checkbox" checked={!!editing.st} onChange={e=>field('st',e.target.checked)}/> Suraksha training</label><label><input type="checkbox" checked={!!editing.ap} onChange={e=>field('ap',e.target.checked)}/> Suraksha AP added</label><label><input type="checkbox" checked={!!editing.project} onChange={e=>field('project',e.target.checked)}/> New Suraksha project</label></div></div><div className="modalfoot"><button type="button" className="cancel" onClick={()=>setModal(false)}>Cancel</button><button disabled={saving}>{saving?'Saving…':editing.id?'Save changes':'Add record'}</button></div></form></div>}
  </div>
}
