export const recordsSchema=`CREATE TABLE IF NOT EXISTS records (
  id TEXT PRIMARY KEY,
  date TEXT NOT NULL,
  fy TEXT NOT NULL,
  month TEXT NOT NULL,
  quarter TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('Active','Completed','Cancelled')),
  remarks TEXT NOT NULL,
  name TEXT,
  mobile TEXT,
  email TEXT,
  designation TEXT,
  id_no TEXT,
  other_details TEXT,
  member TEXT,
  sponsorship REAL NOT NULL DEFAULT 0,
  expenditure REAL NOT NULL DEFAULT 0,
  pacc REAL NOT NULL DEFAULT 0,
  ad REAL NOT NULL DEFAULT 0,
  event TEXT,
  training TEXT,
  article TEXT,
  st INTEGER NOT NULL DEFAULT 0,
  ap INTEGER NOT NULL DEFAULT 0,
  project INTEGER NOT NULL DEFAULT 0,
  nominations INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
)`;
